# Generated by Django 2.2.8 on 2020-01-24 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Transgender')], default=0)),
                ('profile_pic', pyuploadcare.dj.models.ImageField(blank=True)),
                ('bio', models.TextField(max_length=300)),
                ('age', models.IntegerField(choices=[(1, '18-25'), (2, '26-30'), (3, '30-35'), (4, '36-40'), (5, 'Above 40')], default=0)),
                ('complexion', models.IntegerField(choices=[(1, 'Brown'), (2, 'Chocolate'), (3, 'Dark')], default=0)),
                ('personality', models.IntegerField(choices=[(1, 'Introvert'), (2, 'Extrovert')], default=0)),
                ('height', models.IntegerField(choices=[(1, '4 feet'), (2, '5 feet'), (3, '6 feet'), (4, '7 feet')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Transgender')])),
                ('age', models.IntegerField(choices=[(1, '18-25'), (2, '26-30'), (3, '30-35'), (4, '36-40'), (5, 'Above 40')])),
                ('complexion', models.IntegerField(choices=[(1, 'Brown'), (2, 'Chocolate'), (3, 'Dark')])),
                ('personality', models.IntegerField(choices=[(1, 'Introvert'), (2, 'Extrovert')])),
                ('height', models.IntegerField(choices=[(1, '4 feet'), (2, '5 feet'), (3, '6 feet'), (4, '7 feet')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
